version: '3'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy:latest
  ports:
   - 80:80
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  environment:
   - VIRTUAL_PORT=5299
   - VIRTUAL_PORT=8686
   - VIRTUAL_PORT=9117

 lazylibrarian:
  image: linuxserver/lazylibrarian:latest
  restart: always
  ports:
   - 5299:5299
  volumes:
   - /mnt/nas1/docker/lazylibrarian/config:/config
   - /mnt/nas1/docker/downloads:/downloads
   - /mnt/nas1/books:/books
  environment:
   - PUID=1001
   - PGID=1001
   - TZ=America/Phoenix
   - VIRTUAL_HOST=books.bagala.net

 lidarr:
  image: linuxserver/lidarr:latest
  restart: always
  ports:
   - 8686:8686
  volumes:
   - /mnt/nas1/docker/lidarr/config:/config
   - /mnt/nas1/docker/downloads:/downloads
   - /mnt/nas1/music:/music
  environment:
   - PUID=1001
   - PGID=1001
   - TZ=America/Phoenix
   - VIRTUAL_HOST=lidarr.bagala.net

 deluge:
  image: linuxserver/deluge:latest
  restart: always
  network_mode: "host"
  volumes:
   - /mnt/nas1/docker/downloads:/downloads
   - /mnt/nas1/docker/deluge/config:/config
   - /mnt/nas1/docker/watched:/watched
  environment:
   - PUID=1001
   - PGID=1001
   - TZ=America/Phoenix

 jackett:
  image: linuxserver/jackett:latest
  restart: always
  ports:
   - 9117:9117
  volumes:
   - /mnt/nas1/docker/jackett/config:/config
   - /mnt/nas1/docker/jackett/downloads:/downloads
  environment:
   - PUID=1001
   - PGID=1001
   - TZ=America/Phoenix
   - VIRTUAL_HOST=jackett.bagala.net

networks:
 default:
  external:
   name: nginx-proxy
